### ISSUE TITLE
Curious: why extract the embeddings separately? 

### ISSUE THREAD

**Issue by sdinardo** [Dragonmasterx87/Interactive-3D-Plotting-in-Seurat-3.0.0#10]
Code is very helpful; thank you!  

Not an 'issue', but a question:  I just realized that I do not understand a set of entries; why does one pull the embeddings into separate objects?  Example:
umap_1 <- cystLineage2021_10[["umap"]]@cell.embeddings[,1] 
(and two more lines for _2, and _3).  These objects are not actually used for the plot, unless I am missing something obvious.

**Comment by Dragonmasterx87** [comment]
Hello @sdinardo thanks for your comment and I'm glad you find this useful!
So this is a good question, and a simple answer is yes, it is used in the code. The next 2-lines utilizes each of these objects:

```
# Extract tSNE information from Seurat Object
umap_1 <- yourseuratobject[["umap"]]@cell.embeddings[,1]
umap_2 <- yourseuratobject[["umap"]]@cell.embeddings[,2]
umap_3 <- yourseuratobject[["umap"]]@cell.embeddings[,3]

# Visualize what headings are called so that you can extract them to form a dataframe
Embeddings(object = yourseuratobject, reduction = "umap")

# Prepare a dataframe for cell plotting
plot.data <- FetchData(object = yourseuratobject, vars = c("UMAP_1", "UMAP_2", "UMAP_3", "seurat_clusters"))
```

So in Seurat, you automatically calculate 2 sets of PCA coordinates (be it UMAP or tSNE) however in a > 2-dimensional projection of principal components you need to calculate the 3rd set of coordinates (components). The 'z' component if you will. You already have the 'x' and 'y/ components, but you need the 3rd 'z' component in order to project your cells in a 3-dimensional space. Thats why we first run 3-dimensional components:

```
# Re-run UMAPs that you have accurate calculations for all UMAP(s)
yourseuratobject <- RunUMAP(yourseuratobject,
                            dims = 1:10,
                            n.components = 3L) #runs and calculates 3-components 
```

and then we extract and use those coordinates to plot in 3D space.

Hope that helps.

🐲

**Comment by sdinardo** [comment]
@Dragonmasterx87 I very much appreciate the (quick) response!  I have used your code to make (nice) 3D UMAPs (and will def cite you folks in our submission).  

But, I think I was not clear in my question. I understand that after passing the 'n.components = 3L' as an argument to RunUMAP, there will now be three columns, and we want to use those three columns for the axes in a 3D plot.  

I run your code WITHOUT pulling out the following three objects (just comment them out):
umap_1 <- yourseuratobject[["umap"]]@cell.embeddings[,1]
umap_2 <- yourseuratobject[["umap"]]@cell.embeddings[,2]
umap_3 <- yourseuratobject[["umap"]]@cell.embeddings[,3]
And the 3D plot is fine.

So, I use:
--RunUMAP
--FetchData (this already pulls the three UMAP columns without needing to have pulled each out separately, because one argument you have us use for FetchData is: 'vars = c("UMAP_1", "UMAP_2", "UMAP_3",)').
--plotly(data = plot.data, 
        x = ~UMAP_1, y = ~UMAP_2, z = ~UMAP_3, ...)

I am new to this, and may be missing something.  So, I wondered if there was some other reason you separately pull out a Named num for each column of umap values?  i.e., umap_3 <- yourseuratobject[["umap"]]@cell.embeddings[,1]

**Comment by Dragonmasterx87** [comment]
@sdinardo you are 100% correct. Sorry for the misunderstanding on my part. There is absolutely no need to extract the embeddings separately, I think this is some redundant code from a time where tSNE coordinates needed to be extracted as I didn't realize at the time what the coordinates were called or saved as. Thank you for pointing this out and my apologies for the stupidity.

**Comment by sdinardo** [comment]
@Dragonmasterx87 Hah!  Never copt to 'stupidity'!  You should see what my 'code' looks like!!!  In fact, I do not even know how naive and cumbersome my code is - likely, it's filled with archaic manipulations at a minimum, and, let's agree to call them, 'distractions'.  Again, all fine - I'm just happy to know I did understand something.  Cheers!
