### ISSUE TITLE
Making/saving 3D animation

### ISSUE THREAD

**Issue by Gibbatron** [Dragonmasterx87/Interactive-3D-Plotting-in-Seurat-3.0.0#11]
Hi, 

not a problem as such, but I'd like to make this interactive 3D plot into a 3D animation where the plot spins on an axis continually. Is there a way I can do this?

Thanks in advance!

Alex

**Comment by Dragonmasterx87** [comment]
Sorry that I didn't respond to this! Its been a year!
I just haven't had the time, but will add operability for vid recording soon. Right now the most optimal method is to make a video using screen record.
