### ISSUE TITLE
Keep the name of the dataframe consistent

### ISSUE THREAD

**Issue by ishwarvh** [Dragonmasterx87/Interactive-3D-Plotting-in-Seurat-3.0.0#6]
Line 44: The name of the dataframe needs to consistent.  I assume this was a typo!
Keep it either plotting.data or plot.data

**Comment by Dragonmasterx87** [comment]
Thanks for pointing out typos! I went over the typos earlier today please see #5 if I am missing something please point it out! Thanks!

🐲
